### ISSUE TITLE
TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by AmanDubey10198** [Codebrahma/react-notifications-menu#2] opened 2020-10-17 14:10 UTC
Notifications.handleClickOutside
F:/InternshipP2L/student_classroom_management/src/index.js:81
HTMLDocument.<anonymous>
F:/InternshipP2L/student_classroom_management/src/index.js:35

I am getting this error while using react-notifications-menu.

**Comment by servel333** [comment] 2021-01-20 18:37
I'm getting the exact same error. 3 months and no reply. This project could be abandoned.

**Comment by ShafiqueMalik** [comment] 2021-09-10 20:30
what is the solution @servel333

**Comment by servel333** [comment] 2021-09-13 16:51
@ShafiqueMalik I don't have a specific solution. Unfortunately it's been too long for me to remember what I did to solve this. If you need to use this library, it might be a good time to fork this project and patch that one error using the stack trace. You'd be looking for a line like `.contents` and you'll have to look at the code around it and figure out the problem.

**Comment by ShafiqueMalik** [comment] 2021-09-13 20:05
You just find .current property and before using it check it is not null.

**Comment by servel333** [comment] 2021-09-13 20:34
You would need to look in the code for this notification and see what the problem is. It could be it's being called in a way the original author did not anticipate, or it could be an internal error that can only be fixed by updating the extension.

I'm not sure what the problem is though.

Do you have a stack trace?

**Comment by ShafiqueMalik** [comment] 2021-09-13 22:13
I’m not very good in github, but I know the problem after seeing the package code. It throughing error at current property which is null. Just add a null check before doing anything on it.

By the way I developed this component on my own.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ashwinKumar0505** [comment] 2021-11-03 09:47
This issue has been resolved. Sorry for the late fix

**Closed by ashwinKumar0505** 2021-11-03 09:47 UTC

**Comment by ShafiqueMalik** [comment] 2021-11-03 10:36
Great

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by servel333** [comment] 2021-11-08 20:31
Better late than never. Thanks for this.
